# Society Simulation - Docker Compose Configuration
version: '3.8'

services:
  # Main simulation backend
  society-backend:
    build: .
    container_name: society-backend
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - SIMULATION_MODE=headless
      - LOG_LEVEL=info
      - MAX_AGENTS=500
      - AUTO_SAVE_INTERVAL=1000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - society-network

  # Web client (Svelte app)
  society-web:
    build:
      context: ./web_client
      dockerfile: Dockerfile
    container_name: society-web
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000/ws
    depends_on:
      - society-backend
    restart: unless-stopped
    networks:
      - society-network

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: society-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - society-network

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: society-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: unless-stopped
    networks:
      - society-network

  # Grafana for visualization dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: society-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - society-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: society-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - society-backend
      - society-web
    restart: unless-stopped
    networks:
      - society-network

networks:
  society-network:
    driver: bridge

volumes:
  redis-data:
  prometheus-data:
  grafana-data: